name: GitHub Metrics

on:
  # Schedule updates every 24 hours
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering
  workflow_dispatch:
  # Update on every push to main
  push:
    branches: [ main ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: diazrahman21
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Jakarta
          
          # Plugin configuration (simplified)
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_achievements: yes
          plugin_habits: yes
          plugin_activity: yes
